// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package decimal

import (
	"fmt"

	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"

	"github.com/tarantool/go-option"
)

// OptionalDecimal represents an optional value of type Decimal.
// It can either hold a valid Decimal (IsSome == true) or be empty (IsZero == true).
type OptionalDecimal struct {
	value  Decimal
	exists bool
}

// SomeOptionalDecimal creates an optional OptionalDecimal with the given Decimal value.
// The returned OptionalDecimal will have IsSome() == true and IsZero() == false.
func SomeOptionalDecimal(value Decimal) OptionalDecimal {
	return OptionalDecimal{
		value:  value,
		exists: true,
	}
}

// NoneOptionalDecimal creates an empty optional OptionalDecimal value.
// The returned OptionalDecimal will have IsSome() == false and IsZero() == true.
//
// Example:
//
//	o := NoneOptionalDecimal()
//	if o.IsZero() {
//	    fmt.Println("value is absent")
//	}
func NoneOptionalDecimal() OptionalDecimal {
	return OptionalDecimal{}
}

func (o OptionalDecimal) newEncodeError(err error) error {
	if err == nil {
		return nil
	}
	return &option.EncodeError{
		Type:   "OptionalDecimal",
		Parent: err,
	}
}

func (o OptionalDecimal) newDecodeError(err error) error {
	if err == nil {
		return nil
	}

	return &option.DecodeError{
		Type:   "OptionalDecimal",
		Parent: err,
	}
}

// IsSome returns true if the OptionalDecimal contains a value.
// This indicates the value is explicitly set (not None).
func (o OptionalDecimal) IsSome() bool {
	return o.exists
}

// IsZero returns true if the OptionalDecimal does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o OptionalDecimal) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o OptionalDecimal) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of Decimal, false).
//
// Recommended usage:
//
//		if value, ok := o.Get(); ok {
//	     // use value
//		}
func (o OptionalDecimal) Get() (Decimal, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o OptionalDecimal) MustGet() Decimal {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for Decimal.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o OptionalDecimal) Unwrap() Decimal {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
//
// Example:
//
//	o := NoneOptionalDecimal()
//	v := o.UnwrapOr(someDefaultOptionalDecimal)
func (o OptionalDecimal) UnwrapOr(defaultValue Decimal) Decimal {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
//
// Example:
//
//	o := NoneOptionalDecimal()
//	v := o.UnwrapOrElse(func() Decimal { return computeDefault() })
func (o OptionalDecimal) UnwrapOrElse(defaultValue func() Decimal) Decimal {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

func (o OptionalDecimal) encodeValue(encoder *msgpack.Encoder) error {
	value, err := o.value.MarshalMsgpack()
	if err != nil {
		return err
	}

	err = encoder.EncodeExtHeader(1, len(value))
	if err != nil {
		return err
	}

	_, err = encoder.Writer().Write(value)
	if err != nil {
		return err
	}

	return nil
}

// EncodeMsgpack encodes the OptionalDecimal value using MessagePack format.
// - If the value is present, it is encoded as Decimal.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o OptionalDecimal) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return o.newEncodeError(o.encodeValue(encoder))
	}

	return o.newEncodeError(encoder.EncodeNil())
}

func (o *OptionalDecimal) decodeValue(decoder *msgpack.Decoder) error {
	tp, length, err := decoder.DecodeExtHeader()
	switch {
	case err != nil:
		return o.newDecodeError(err)
	case tp != 1:
		return o.newDecodeError(fmt.Errorf("invalid extension code: %d", tp))
	}

	a := make([]byte, length)
	if err := decoder.ReadFull(a); err != nil {
		return o.newDecodeError(err)
	}

	if err := o.value.UnmarshalMsgpack(a); err != nil {
		return o.newDecodeError(err)
	}

	o.exists = true
	return nil
}

func (o *OptionalDecimal) checkCode(code byte) bool {
	return msgpcode.IsExt(code)
}

// DecodeMsgpack decodes a OptionalDecimal value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneOptionalDecimal)
//   - Decimal: interpreted as a present value (SomeOptionalDecimal)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on Decimal: exists = true, value = decoded value
func (o *OptionalDecimal) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return o.newDecodeError(err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return o.newDecodeError(decoder.Skip())
	case o.checkCode(code):
		err := o.decodeValue(decoder)
		if err != nil {
			return o.newDecodeError(err)
		}
		o.exists = true

		return err
	default:
		return o.newDecodeError(fmt.Errorf("unexpected code: %d", code))
	}
}
