// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package uuid

import (
	"github.com/google/uuid"

	"fmt"

	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"

	"github.com/tarantool/go-option"
)

// OptionalUUID represents an optional value of type uuid.UUID.
// It can either hold a valid uuid.UUID (IsSome == true) or be empty (IsZero == true).
type OptionalUUID struct {
	value  uuid.UUID
	exists bool
}

// SomeOptionalUUID creates an optional OptionalUUID with the given uuid.UUID value.
// The returned OptionalUUID will have IsSome() == true and IsZero() == false.
func SomeOptionalUUID(value uuid.UUID) OptionalUUID {
	return OptionalUUID{
		value:  value,
		exists: true,
	}
}

// NoneOptionalUUID creates an empty optional OptionalUUID value.
// The returned OptionalUUID will have IsSome() == false and IsZero() == true.
//
// Example:
//
//	o := NoneOptionalUUID()
//	if o.IsZero() {
//	    fmt.Println("value is absent")
//	}
func NoneOptionalUUID() OptionalUUID {
	return OptionalUUID{}
}

func (o OptionalUUID) newEncodeError(err error) error {
	if err == nil {
		return nil
	}
	return &option.EncodeError{
		Type:   "OptionalUUID",
		Parent: err,
	}
}

func (o OptionalUUID) newDecodeError(err error) error {
	if err == nil {
		return nil
	}

	return &option.DecodeError{
		Type:   "OptionalUUID",
		Parent: err,
	}
}

// IsSome returns true if the OptionalUUID contains a value.
// This indicates the value is explicitly set (not None).
func (o OptionalUUID) IsSome() bool {
	return o.exists
}

// IsZero returns true if the OptionalUUID does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o OptionalUUID) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o OptionalUUID) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of uuid.UUID, false).
//
// Recommended usage:
//
//		if value, ok := o.Get(); ok {
//	     // use value
//		}
func (o OptionalUUID) Get() (uuid.UUID, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o OptionalUUID) MustGet() uuid.UUID {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for uuid.UUID.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o OptionalUUID) Unwrap() uuid.UUID {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
//
// Example:
//
//	o := NoneOptionalUUID()
//	v := o.UnwrapOr(someDefaultOptionalUUID)
func (o OptionalUUID) UnwrapOr(defaultValue uuid.UUID) uuid.UUID {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
//
// Example:
//
//	o := NoneOptionalUUID()
//	v := o.UnwrapOrElse(func() uuid.UUID { return computeDefault() })
func (o OptionalUUID) UnwrapOrElse(defaultValue func() uuid.UUID) uuid.UUID {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

func (o OptionalUUID) encodeValue(encoder *msgpack.Encoder) error {
	value, err := marshalUUID(o.value)
	if err != nil {
		return err
	}

	err = encoder.EncodeExtHeader(2, len(value))
	if err != nil {
		return err
	}

	_, err = encoder.Writer().Write(value)
	if err != nil {
		return err
	}

	return nil
}

// EncodeMsgpack encodes the OptionalUUID value using MessagePack format.
// - If the value is present, it is encoded as uuid.UUID.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o OptionalUUID) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return o.newEncodeError(o.encodeValue(encoder))
	}

	return o.newEncodeError(encoder.EncodeNil())
}

func (o *OptionalUUID) decodeValue(decoder *msgpack.Decoder) error {
	tp, length, err := decoder.DecodeExtHeader()
	switch {
	case err != nil:
		return o.newDecodeError(err)
	case tp != 2:
		return o.newDecodeError(fmt.Errorf("invalid extension code: %d", tp))
	}

	a := make([]byte, length)
	if err := decoder.ReadFull(a); err != nil {
		return o.newDecodeError(err)
	}

	if err := unmarshalUUID(&o.value, a); err != nil {
		return o.newDecodeError(err)
	}

	o.exists = true
	return nil
}

func (o *OptionalUUID) checkCode(code byte) bool {
	return msgpcode.IsExt(code)
}

// DecodeMsgpack decodes a OptionalUUID value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneOptionalUUID)
//   - uuid.UUID: interpreted as a present value (SomeOptionalUUID)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on uuid.UUID: exists = true, value = decoded value
func (o *OptionalUUID) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return o.newDecodeError(err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return o.newDecodeError(decoder.Skip())
	case o.checkCode(code):
		err := o.decodeValue(decoder)
		if err != nil {
			return o.newDecodeError(err)
		}
		o.exists = true

		return err
	default:
		return o.newDecodeError(fmt.Errorf("unexpected code: %d", code))
	}
}
