// Code generated by github.com/tarantool/go-option; DO NOT EDIT.

package datetime

import (
	"fmt"

	"github.com/vmihailenco/msgpack/v5"
	"github.com/vmihailenco/msgpack/v5/msgpcode"

	"github.com/tarantool/go-option"
)

// OptionalInterval represents an optional value of type Interval.
// It can either hold a valid Interval (IsSome == true) or be empty (IsZero == true).
type OptionalInterval struct {
	value  Interval
	exists bool
}

// SomeOptionalInterval creates an optional OptionalInterval with the given Interval value.
// The returned OptionalInterval will have IsSome() == true and IsZero() == false.
func SomeOptionalInterval(value Interval) OptionalInterval {
	return OptionalInterval{
		value:  value,
		exists: true,
	}
}

// NoneOptionalInterval creates an empty optional OptionalInterval value.
// The returned OptionalInterval will have IsSome() == false and IsZero() == true.
//
// Example:
//
//	o := NoneOptionalInterval()
//	if o.IsZero() {
//	    fmt.Println("value is absent")
//	}
func NoneOptionalInterval() OptionalInterval {
	return OptionalInterval{}
}

func (o OptionalInterval) newEncodeError(err error) error {
	if err == nil {
		return nil
	}
	return &option.EncodeError{
		Type:   "OptionalInterval",
		Parent: err,
	}
}

func (o OptionalInterval) newDecodeError(err error) error {
	if err == nil {
		return nil
	}

	return &option.DecodeError{
		Type:   "OptionalInterval",
		Parent: err,
	}
}

// IsSome returns true if the OptionalInterval contains a value.
// This indicates the value is explicitly set (not None).
func (o OptionalInterval) IsSome() bool {
	return o.exists
}

// IsZero returns true if the OptionalInterval does not contain a value.
// Equivalent to !IsSome(). Useful for consistency with types where
// zero value (e.g. 0, false, zero struct) is valid and needs to be distinguished.
func (o OptionalInterval) IsZero() bool {
	return !o.exists
}

// IsNil is an alias for IsZero.
//
// This method is provided for compatibility with the msgpack Encoder interface.
func (o OptionalInterval) IsNil() bool {
	return o.IsZero()
}

// Get returns the stored value and a boolean flag indicating its presence.
// If the value is present, returns (value, true).
// If the value is absent, returns (zero value of Interval, false).
//
// Recommended usage:
//
//		if value, ok := o.Get(); ok {
//	     // use value
//		}
func (o OptionalInterval) Get() (Interval, bool) {
	return o.value, o.exists
}

// MustGet returns the stored value if it is present.
// Panics if the value is absent (i.e., IsZero() == true).
//
// Use with caution — only when you are certain the value exists.
//
// Panics with: "optional value is not set" if no value is set.
func (o OptionalInterval) MustGet() Interval {
	if !o.exists {
		panic("optional value is not set")
	}

	return o.value
}

// Unwrap returns the stored value regardless of presence.
// If no value is set, returns the zero value for Interval.
//
// Warning: Does not check presence. Use IsSome() before calling if you need
// to distinguish between absent value and explicit zero value.
func (o OptionalInterval) Unwrap() Interval {
	return o.value
}

// UnwrapOr returns the stored value if present.
// Otherwise, returns the provided default value.
//
// Example:
//
//	o := NoneOptionalInterval()
//	v := o.UnwrapOr(someDefaultOptionalInterval)
func (o OptionalInterval) UnwrapOr(defaultValue Interval) Interval {
	if o.exists {
		return o.value
	}

	return defaultValue
}

// UnwrapOrElse returns the stored value if present.
// Otherwise, calls the provided function and returns its result.
// Useful when the default value requires computation or side effects.
//
// Example:
//
//	o := NoneOptionalInterval()
//	v := o.UnwrapOrElse(func() Interval { return computeDefault() })
func (o OptionalInterval) UnwrapOrElse(defaultValue func() Interval) Interval {
	if o.exists {
		return o.value
	}

	return defaultValue()
}

func (o OptionalInterval) encodeValue(encoder *msgpack.Encoder) error {
	value, err := o.value.MarshalMsgpack()
	if err != nil {
		return err
	}

	err = encoder.EncodeExtHeader(6, len(value))
	if err != nil {
		return err
	}

	_, err = encoder.Writer().Write(value)
	if err != nil {
		return err
	}

	return nil
}

// EncodeMsgpack encodes the OptionalInterval value using MessagePack format.
// - If the value is present, it is encoded as Interval.
// - If the value is absent (None), it is encoded as nil.
//
// Returns an error if encoding fails.
func (o OptionalInterval) EncodeMsgpack(encoder *msgpack.Encoder) error {
	if o.exists {
		return o.newEncodeError(o.encodeValue(encoder))
	}

	return o.newEncodeError(encoder.EncodeNil())
}

func (o *OptionalInterval) decodeValue(decoder *msgpack.Decoder) error {
	tp, length, err := decoder.DecodeExtHeader()
	switch {
	case err != nil:
		return o.newDecodeError(err)
	case tp != 6:
		return o.newDecodeError(fmt.Errorf("invalid extension code: %d", tp))
	}

	a := make([]byte, length)
	if err := decoder.ReadFull(a); err != nil {
		return o.newDecodeError(err)
	}

	if err := o.value.UnmarshalMsgpack(a); err != nil {
		return o.newDecodeError(err)
	}

	o.exists = true
	return nil
}

func (o *OptionalInterval) checkCode(code byte) bool {
	return msgpcode.IsExt(code)
}

// DecodeMsgpack decodes a OptionalInterval value from MessagePack format.
// Supports two input types:
//   - nil: interpreted as no value (NoneOptionalInterval)
//   - Interval: interpreted as a present value (SomeOptionalInterval)
//
// Returns an error if the input type is unsupported or decoding fails.
//
// After successful decoding:
//   - on nil: exists = false, value = default zero value
//   - on Interval: exists = true, value = decoded value
func (o *OptionalInterval) DecodeMsgpack(decoder *msgpack.Decoder) error {
	code, err := decoder.PeekCode()
	if err != nil {
		return o.newDecodeError(err)
	}

	switch {
	case code == msgpcode.Nil:
		o.exists = false

		return o.newDecodeError(decoder.Skip())
	case o.checkCode(code):
		err := o.decodeValue(decoder)
		if err != nil {
			return o.newDecodeError(err)
		}
		o.exists = true

		return err
	default:
		return o.newDecodeError(fmt.Errorf("unexpected code: %d", code))
	}
}
